# Generated by Django 3.2.3 on 2021-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelterApp', '0002_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('Kitty', 'cat'), ('Doggy', 'dog'), ('Smaller animals', 'small')], default='cat', max_length=20),
        ),
    ]
