# Generated by Django 3.2.3 on 2021-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelterApp', '0004_auto_20210612_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='height',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='weight',
        ),
    ]
