# Generated by Django 3.2.3 on 2021-06-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelterApp', '0006_auto_20210612_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='height',
            field=models.CharField(default='0.5m', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.CharField(default='2.0kg', max_length=10),
        ),
    ]
