# Generated by Django 3.2.3 on 2021-06-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimalShelterApp', '0007_auto_20210612_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.CharField(default='', max_length=250),
        ),
    ]
